TOOLCHAIN_OUT_PATH=$HOME/EagleOS
export TOOLCHAIN_PREFIX="$TOOLCHAIN_OUT_PATH/Opt/Cross"
export TOOLCHAIN_TARGET=i686-elf
export TOOLCHAIN_PATH="$TOOLCHAIN_PREFIX/bin"
export PATH="$TOOLCHAIN_PATH:$PATH"

mkdir Build
cd Build
cmake ..
make -j12
